import assert from "node:assert/strict";
import { readFile, readdir } from "node:fs/promises";
import path from "node:path";
import test from "node:test";
async function walk(directory) { const entries = await readdir(directory, { withFileTypes: true }); const result = []; for (const entry of entries) { const target = path.join(directory, entry.name); if (entry.isDirectory()) result.push(...await walk(target)); else if (target.endsWith(".html")) result.push(target); } return result; }
function primaryNav(html) { return html.match(/<nav aria-label="Primary navigation">([\s\S]*?)<\/nav>/)?.[0]; }
test("generated public pages use identical navigation", async () => { const files = (await walk("dist")).filter((file) => !file.includes(`${path.sep}admin${path.sep}`)); const navs = []; for (const file of files) { const nav = primaryNav(await readFile(file, "utf8")); if (nav) navs.push(nav); } assert.ok(navs.length >= 4); navs.forEach((nav) => assert.equal(nav, navs[0])); });
test("critical content is present without JavaScript", async () => { for (const file of (await walk("dist")).filter((item) => !item.includes(`${path.sep}admin${path.sep}`))) { const html = await readFile(file, "utf8"); assert.match(html, /<main\b/); assert.match(html, /<h1\b/); assert.match(html, /href="\/contact\/"/); } });
test("all internal template types build as complete fixtures", async () => { for (const name of ["product", "institutional", "partner", "resource-listing", "resource-detail", "public-form", "login", "portal"]) { const html = await readFile(path.join(".build", "fixtures", `${name}.html`), "utf8"); assert.match(html, /<!doctype html>/i); assert.match(html, /<main\b/); assert.match(html, /<h1\b/); assert.doesNotMatch(html, /{{[^}]+}}/); } });
test("shared contact configuration is approved", async () => { const config = JSON.parse(await readFile("src/data/site.json", "utf8")); assert.equal(config.whatsapp, "2349151142355"); assert.equal(config.googlePlay, "https://play.google.com/store/apps/details?id=com.myminervahub.nobles_vault"); });
